# Built with Jekyll 3.2.0

# Setup
title:               Km.
tagline:             '知识及注意力管理社群'
description:         'Km 不仅仅针对知识以及其载体, 更加关注使用/生产/传播知识的人以及组织以及过程中注意力消耗的规模.'
#url:                 'http://minicomp.github.io'
baseurl:             '/km'

# About/contact
author:
  name:              DAMA
  url:               https://github.com/ZoomQuiet
  email:             zoomquiet+km@gmail.com

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "cayman"
